### ISSUE TITLE
detect mousewheel rotation?

### ISSUE THREAD

**Issue by netcodeyyy** [tesselode/baton#10]
i didnt find a way on how to detect mousewheel rotation with baton, but this could also be due to me being stupid. Is there detection for it atm? and if not could you pls (pls, pls) add it cuz it would make baton even better and the perfect fit for what i plan on doing

**Comment by tesselode** [comment]
There is not currently detection for mousewheel rotation. Unfortunately, I don't think there's any way for me to add support for it in a way that fits neatly into the current design of Baton. First of all, mousewheel rotation isn't a button - the rotation only happens at one moment in time and you can't "hold it down," so it's a fundamentally different kind of input than every other input Baton supports, and second, Baton would need extra code to use LÖVE's callbacks to even detect the rotation. As nice as it would be to have one library handle every input situation, in the interest of elegant design, I'm going to say that detecting mousewheel rotation is out of scope for this library.

That being said, if you do think of a really clever way to make it work, let me know!
