### ISSUE TITLE
versioning?

### ISSUE THREAD

**Issue by Alloyed** [tesselode/baton#13]
hey hi I'm going to use baton in my game btw

It would be nice if specific versions were tagged though so I can pin them using loverocks: if you've never used git tags before here's a quick tutorial
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by tesselode** [comment]
yeah i'm a little hesitant to start versioning until i'm confident that the API isn't going to change much. when i add version numbers it feels like a guarantee of quality and stability, you know?

**Comment by Positive07** [comment]
Baton is pretty stable and bug free so you should just put a number in there, and if you happen to break it you can just change the major, no one will complain

(Also in Lua we care really little about versions, we generally have a custom copy of the file and that is it)

**Comment by Positive07** [comment]
Fixed in e85d5fa

**Comment by tesselode** [comment]
gOOd point
