### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by williams1** [tesselode/baton#20]
There's a typo in line 64 of main.lua. As written, when the user presses tab, love produces the error "attempt to index field 'controls' (a nil value)"

Changing the line to `player.config.controls.action[1] = 'key:z'` makes it run as intended.

**Comment by tesselode** [comment]
oof! i need to go back and clean up the test project for sure

**Comment by tesselode** [comment]
removed that bit in 72a2bd because it wasn't super relevant to the demo anyway
