### ISSUE TITLE
Add an axis pair object

### ISSUE THREAD

**Issue by tesselode** [tesselode/baton#9]

**Comment by oniietzschan** [comment]
I've gotten some good use out of this library and was thinking of adding this feature and then sending you a PR. I'm wondering what you think about this as an interface:

```lua
local player = baton.new(
  {
    jump  = {'button:a', 'key:z'},
    shoot = {'button:x', 'key:x'},
    move = {
      xpos = {'axis:leftx+', 'key:right'},
      xneg = {'axis:leftx-', 'key:left'},
      ypos = {'axis:lefty+', 'key:down'},
      yneg = {'axis:lefty-', 'key:up'},
    },
  },
  love.joystick.getJoysticks()[1]
)

local x, y = player:get('move')
```

It's the most consistent thing I could come up, but perhaps you have a better idea of how axis pairs might be defined in the control arrays?

**Comment by tesselode** [comment]
Hmmm....so any control with four nested controls will be considered an axis pair? What if you still want to access the individual up/down/left/right controls?

**Comment by oniietzschan** [comment]
1. A `type` key could be added to the nested table with a value of `'axispair'`, and different input aggregates could be supported in the future.

2. That's a good point. It probably makes more sense to define four individual controls outside of the axispair table first, then reference them from inside of the nested table. This would even allow a control to be used inside multiple axispairs if one was so inclined.

Does this make more sense to you?

```lua
local controls = {
  jump  = {'button:a', 'key:z'},
  shoot = {'button:x', 'key:x'},
  right = {'axis:leftx+', 'key:right'},
  left = {'axis:leftx-', 'key:left'},
  down = {'axis:lefty+', 'key:down'},
  up = {'axis:lefty-', 'key:up'},
  move = {
    type = 'axispair',
    xpos = 'right',
    xneg = 'left',
    ypos = 'down',
    yneg = 'up',
  },
}
```

**Comment by tesselode** [comment]
Why not make axis pairs one of the types of controls, just like `button` or `axis`?

```lua
local controls = {
  jump  = {'button:a', 'key:z'},
  shoot = {'button:x', 'key:x'},
  right = {'axis:leftx+', 'key:right'},
  left = {'axis:leftx-', 'key:left'},
  down = {'axis:lefty+', 'key:down'},
  up = {'axis:lefty-', 'key:up'},
  move = {'pair:left,right,down,up'},
}
```

There is going to be a problem with deadzones, though: if someone holds down left, for example, on the keyboard, then miniscule vertical movements on the analog stick will be captured, assuming we're using a circular deadzone for axis pairs, which is the whole point. Still not sure what to do about that, other than define an extra deadzone for axis pairs (or just use some default like deadzone / 2?).

Let me know if that doesn't make sense, it's kind of hard to explain.

**Comment by oniietzschan** [comment]
Ah, I like your syntax best. I have something which works right now using the syntax I posted above, but I'll update it to match yours.

I totally understand what you're saying regarding the deadzones. Right now I'm just doing something rather simplistic which happens to solve that issue. Namely:

```
return math.abs(x) > self.deadzone and x or 0,
           math.abs(y) > self.deadzone and y or 0
```

But this isn't necessarily ideal since it tends to "lock" the angle to 90 degree intervals when you are close to those angles. This happened to be the behavior I wanted for my most recent application, but I don't think it's a great default behavior.

I think the best thing to do would be measure the length of the vector (x, y) and `return 0, 0` when that length is `<= self.deadzone`. Do you agree?

**Comment by tesselode** [comment]
I think we're talking about different problems. So, with an axis pair, let's assume that the behavior is to use a circular deadzone - that is, the x and y controls do not have an individual deadzone, but rather, as long as the length of the vector is more than the deadzone, then the input is used. The problem is, we have no way of differentiating between different input methods. So, if both the arrow keys and analog stick are mapped to up, down, left, and right, then if we hold down the up arrow key, any horizontal analog stick input is going to be picked up, since the length of the vector is more than the deadzone by virtue of holding down an arrow key. However, we don't want all of the analog stick input. Analog sticks are finicky, they don't stay completely centered, etc. So all of this extra horizontal input is going to be picked up because we're not using individual deadzones

**Comment by oniietzschan** [comment]
Oh, right. I got what you were saying the first time, but I just didn't think through my proposed solution well enough to realize that merely measuring the length of the deadzone would not work.

I think we want something like this:

```
local length = math.sqrt(x^2, y^2)
if length <= self.deadzone then
  return 0, 0
end

return math.abs(x) > self.pairDeadzone and x or 0,
       math.abs(y) > self.pairDeadzone and y or 0
```

Does this look right?

**Comment by tesselode** [comment]
yeah, that looks reasonable!

**Comment by oniietzschan** [comment]
I've submitted a PR, please have a look when you can: https://github.com/tesselode/baton/pull/11

**Comment by tesselode** [comment]
Baton now has axis pairs as of 9465349.
